server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: cache static assets aggressively
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}

server {
    listen 80;
    server_name care.internal;

    return 301 https://care.local.ssmmhospital.com$request_uri;
}
