module NursingCare = CriticalCare__NursingCare
module HemodynamicParameters = CriticalCare__HemodynamicParameters
module ABGAnalysis = CriticalCare__ABGAnalysis
module BloodSugar = CriticalCare_BloodSugar
