module NursingCare = CriticalCare__NursingCare
module HemodynamicParameters = CriticalCare__HemodynamicParameters
module ABGAnalysis = CriticalCare__ABGAnalysis
module VentilatorParameters = CriticalCare__VentilatorParameters
