name: Cypress Tests

on:
  pull_request:
    branches:
      - develop
      - staging
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.13.0-chrome-132.0.6834.83-1-ff-134.0.1-edge-131.0.2903.147-1
      options: --user 1001
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: build

  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.13.0-chrome-132.0.6834.83-1-ff-134.0.1-edge-131.0.2903.147-1
      options: --user 1001
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4

      - name: Determine PR Origin
        id: pr_origin
        run: echo "::set-output name=is_forked::$( echo ${{ github.event.pull_request.head.repo.fork }})"

      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      # For non-forked PRs
      - name: "UI Tests - Chrome (Non-forked)"
        if: steps.pr_origin.outputs.is_forked == 'false'
        uses: cypress-io/github-action@v6
        with:
          start: "npx vite preview --host"
          wait-on: "http://localhost:4000"
          wait-on-timeout: 300
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome"
          config-file: cypress.config.ts
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: --max_old_space_size=4096
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}

      # For forked PRs
      - name: "UI Tests - Chrome (Forked)"
        if: steps.pr_origin.outputs.is_forked == 'true'
        uses: cypress-io/github-action@v6
        with:
          start: "npx vite preview --host"
          wait-on: "http://localhost:4000"
          wait-on-timeout: 300
          browser: chrome
          record: false
          parallel: true
          group: "UI - Chrome"
          config-file: cypress.config.ts
        env:
          CYPRESS_SPLIT_TESTS: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: --max_old_space_size=4096
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}

      - name: Upload cypress screenshots on failure 📸
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload cypress videos 📹
        uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.pr_origin.outputs.is_forked == 'true' }}
        with:
          name: cypress-videos
          path: cypress/videos
