name: Cypress Tests

on:
  pull_request:
    branches:
      - develop
      - staging
  workflow_dispatch:

jobs:
  setup_and_test:
    name: Setup and Run Cypress Tests
    if: github.repository == 'ohcnetwork/care_fe'  # Ensures job runs only for the care_fe repository
    runs-on: ubuntu-latest
    env:
      REACT_CARE_API_URL: http://localhost:9000
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Backend Branch
        id: backend-branch
        run: |
          if [[ '${{ github.event.pull_request.base.ref }}' == 'staging' ]]; then
            echo "branch=staging" >> $GITHUB_OUTPUT
          else
            echo "branch=develop" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Backend Repository
        uses: actions/checkout@v3
        with:
          repository: ohcnetwork/care
          path: care
          ref: ${{ steps.backend-branch.outputs.branch }}

      - name: Start Backend Services
        run: |
          cd care
          echo DISABLE_RATELIMIT=True >> docker/.prebuilt.env
          echo "CORS_ALLOWED_ORIGINS=\"[\\\"http://localhost:4000\\\"]\"" >> docker/.prebuilt.env
          echo JWKS_BASE64=\"$(cat ../.github/runner-files/jwks.b64.txt)\" >> docker/.prebuilt.env
          docker-compose -f docker-compose.pre-built.yaml up -d
          docker-compose -f docker-compose.pre-built.yaml load-dummy-data
          cd ..
        env:
          JWKS_BASE64: ${{ secrets.JWKS_BASE64 }}

      - name: Wait for Backend to be Up
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 10
          command: curl -o /dev/null -s -w "%{http_code}\n" http://localhost:9000
          on_retry_command: sleep 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci
          cd ..

      - name: Build Frontend
        run: |
          cd frontend
          npm run build
          cd ..

      - name: Determine PR Origin
        id: pr_origin
        run: echo "::set-output name=is_forked::$( echo ${{ github.event.pull_request.head.repo.fork }})"

      - name: Run Cypress Tests
        run: |
          cd frontend
          if [ "${{ steps.pr_origin.outputs.is_forked }}" == "false" ]; then
            npx cypress run --parallel --record --group "UI-Chrome" --ci-build-id ${{ github.run_id }} --spec "cypress/e2e/**/*.cy.ts"
          else
            npx cypress-split run --group "UI-Chrome" --ci-build-id ${{ github.run_id }} --spec "cypress/e2e/**/*.cy.ts" --env CYPRESS_SPLIT_TESTS="true"
          fi
        env:
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Upload Cypress Screenshots on Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots

      - name: Upload Cypress Videos
        if: failure() && steps.pr_origin.outputs.is_forked == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: frontend/cypress/videos
