name: Cypress Tests

on:
  pull_request:
    branches:
      - develop
      - staging
  workflow_dispatch:

jobs:
  setup:
    name: Setup Backend and Frontend
    if: github.repository == 'ohcnetwork/care_fe'  # Ensures job runs only for the care_fe repository
    runs-on: ubuntu-latest
    outputs:
      backend_url: ${{ steps.backend-url.outputs.backend_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Set Backend Branch
        id: backend-branch
        run: |
          if [[ '${{ github.event.pull_request.base.ref }}' == 'staging' ]]; then
            echo "branch=staging" >> $GITHUB_OUTPUT
          else
            echo "branch=develop" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Backend Repository
        uses: actions/checkout@v3
        with:
          repository: ohcnetwork/care
          path: repo/care
          ref: ${{ steps.backend-branch.outputs.branch }}

      - name: Start Backend Services
        run: |
          cd repo/care
          echo DISABLE_RATELIMIT=True >> docker/.prebuilt.env
          echo "CORS_ALLOWED_ORIGINS=\"[\\\"http://localhost:4000\\\"]\"" >> docker/.prebuilt.env
          echo JWKS_BASE64=\"$(cat ../.github/runner-files/jwks.b64.txt)\" >> docker/.prebuilt.env
          docker-compose -f docker-compose.pre-built.yaml up -d
          cd ..
        env:
          JWKS_BASE64: ${{ secrets.JWKS_BASE64 }}

      - name: Wait for Backend to be Up
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 10
          command: curl -o /dev/null -s -w "%{http_code}\n" http://localhost:9000
          on_retry_command: sleep 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: repo/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('repo/frontend/package-lock.json') }}

      - name: Install Frontend Dependencies
        run: |
          cd repo/frontend
          npm ci
          cd ../..

      - name: Build Frontend
        run: |
          cd repo/frontend
          npm run build
          cd ../..

  test:
    name: Run Cypress Tests
    if: github.repository == 'ohcnetwork/care_fe'  # Ensures job runs only for the care_fe repository
    needs: setup
    runs-on: ubuntu-latest
    env:
      REACT_CARE_API_URL: http://localhost:9000
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Determine PR Origin
        id: pr_origin
        run: echo "::set-output name=is_forked::$( echo ${{ github.event.pull_request.head.repo.fork }})"

      - name: Wait for Backend Health Check
        run: |
          for i in {1..10}; do
            response=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:9000/health)
            if [ "$response" -eq 200 ]; then
              echo "Backend is healthy!"
              break
            else
              echo "Waiting for backend to be healthy..."
              sleep 10
            fi
          done

      - name: Cypress Run for Non-Forked PRs
        if: steps.pr_origin.outputs.is_forked == 'false'
        run: |
          cd repo/frontend
          npx cypress run --parallel --record --group "UI-Chrome" --ci-build-id ${{ github.run_id }} --spec "cypress/e2e/**/*.cy.ts"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          NODE_OPTIONS: --max_old_space_size=4096
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Cypress Run for Forked PRs
        if: steps.pr_origin.outputs.is_forked == 'true'
        run: |
          cd repo/frontend
          npx cypress-split run --group "UI-Chrome" --ci-build-id ${{ github.run_id }} --spec "cypress/e2e/**/*.cy.ts" --env CYPRESS_SPLIT_TESTS="true"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          NODE_OPTIONS: --max_old_space_size=4096
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Upload Cypress Screenshots on Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: repo/frontend/cypress/screenshots

      - name: Upload Cypress Videos
        if: failure() && steps.pr_origin.outputs.is_forked == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: repo/frontend/cypress/videos
