name: Deploy Care Fe

on:
  push:
    branches:
      - develop
      - staging
    tags:
      - v*
  pull_request:
    branches:
      - develop
      - staging
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  IMAGE_NAME: care_fe

jobs:
  test:
    if: github.repository == 'ohcnetwork/care_fe'
    runs-on: ubuntu-24.04-arm
    name: Test
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          provenance: false
          cache-from: type=gha,scope=care-fe-test
          cache-to: type=gha,mode=max,scope=care-fe-test
